# roles/example/tasks/main.yml
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family |lower }}.yml"

- name: Install the correct web server for RHEL
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

