---
- name: update apt cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
- name: Install web server
  ansible.builtin.apt:
    name: "{{ package_name }}"
    state: present
  register: output

- debug: var=output
- name: start web service
  service:
    name: "{{ package_name }}"
    state: started
    enabled: true
  register: output

- debug: var=output
