playbook.yml to install and start two services using yum module  - 
cat playbook.yml
---
- name: install and start two services using yum module
  hosts: test
  become: yes
  
  vars:
    packages:
      - htop
      - docker
  
  tasks:
    - name: install ntpd and nginx
      yum: 
        name: "{{ packages }}"
        state: present
    - name: start serive
      service:
      name: "{{ packages }}"
      state: started
      enabled: true
      
      
--- or 

playbook.yml to install and start service using yum module  - 
cat playbook.yml
---
- name: install and start two services using yum module
  hosts: test
  become: yes
  
  vars:
    package_name: httpd
  tasks:
    - name: install ntpd and nginx
      yum:
       name: "{{ package_name }}"
       state: present
		   
    - name: start serive
      service:
      name: "{{ package_name }}"
      state: started
      enabled: true 
