#playbook.yml to encrypt a variable using ansible vault in localhost   - 
#cat playbook.yml
---
- name: encrypt a variable
  hosts: localhost
  connection: no
  
  vars_files:
    - vars/api_key.yml
  
  tasks:
    - name: Echo a variable to test encryption
      shell: echo $MY_KEY
      environment:
        MY_KEY: "{{ myapp_key }}"
      register: echo_result
      
    - name: Show the result
      debug: var=echo_result.stdout

