# roles/example/tasks/main.yml
- name: Install the correct web server for RHEL
  vars:
    package_name: httpd
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  import_tasks: debian.yml
  vars:
    package_name: apache2
  when: ansible_facts['os_family']|lower == 'debian'

