# roles/example/tasks/redhat.yml
- name: Install web server
  ansible.builtin.yum:
    name: "{{ package_name }}"
    state: present
- name: start web service
  service:
    name: "{{ package_name }}"
    state: started
    enabled: true
  register: output
- debug: var=output
